python3 test.py -s Success!! -f output/test1.txt
python3 test.py -s Success!! -f output/test2.txt
python3 test.py -s Success!! -f output/test3.txt
python3 test.py -s Success!! -f output/test4.txt
python3 test.py -s Success!! -f output/test5.txt
python3 test.py -s Success!! -f output/test6.txt
python3 test.py -s Success!! -f output/test7.txt
python3 test.py -s Success!! -f output/test8.txt
python3 test.py -s Success!! -f output/test9.txt
python3 test.py -s Success!! -f output/test10.txt
python3 test.py -s Success!! -f output/test11.txt
python3 test.py -s Success!! -f output/test12.txt
python3 test.py -s Success!! -f output/test13.txt
python3 test.py -s Success!! -f output/test14.txt
python3 test.py -s Success!! -f output/test15.txt
python3 test.py -s Success!! -f output/test16.txt
python3 test.py -s Success!! -f output/test17.txt
python3 test.py -s Success!! -f output/test18.txt
python3 test.py -s Success!! -f output/test19.txt